---
# tasks file for nginx
- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
    state: present
  become: true

- name: Copy proxy cfg
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nginxconfig"
    dest: /etc/nginx/sites-available/default
  become: true

- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: restarted
  become: true  
